### ISSUE TITLE
Come join project?

### ISSUE THREAD

**Issue by andymac4182** [Mahmoud-zino/ObsidianToConfluence#10]
Hey,

I have a similar project and curious if you would like to come join. 

https://github.com/obsidian-confluence/obsidian-confluence
https://obsidian-confluence.com/
https://www.npmjs.com/package/@markdown-confluence/cli

Sorry I don't have another way to contact you.

Cheers,
Andrew

**Comment by Mahmoud-zino** [comment]
I would love to
